#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

dns_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4, $5}')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_info "$1" "www"
  dns_info "$1" "lb-01"
  dns_info "$1" "web-01"
  dns_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_info "$1" "$2"
fi
