#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

DNS_info () {
    # Get the DNS information and check if there is an answer section
    ANSWER=$(dig "$2" +noall +answer)
    
    if [[ -z "$ANSWER" ]]; then
        echo "No DNS record found for $2"
        return
    fi
    
    # Extract the type (A, CNAME, etc.) and the IP address or domain it points to
    RECORD_TYPE=$(echo "$ANSWER" | awk '{print $4}')
    RECORD_VALUE=$(echo "$ANSWER" | awk '{print $5}')
    
    if [[ -n "$RECORD_TYPE" && -n "$RECORD_VALUE" ]]; then
        echo "The subdomain $1 is a $RECORD_TYPE record and points to $RECORD_VALUE"
    else
        echo "Could not retrieve the DNS information correctly for $2"
    fi
}

if [[ $# == 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${subdomains[@]}"; do
        CONCAT="$i.$1"
        DNS_info "$i" "$CONCAT"
    done
else
    CONCAT="$2.$1"
    DNS_info "$2" "$CONCAT"
fi

