#!/usr/bin/env bash
# Transfers a file from our cliennt to a server
# (must transfer the file to the user home directory ~/)
# Accepts 4 parameters:
    # Path to the file to be transferred
    # IP of the server to transfer to
    # Username scp connects with
    # Path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# Strict host key checking must be disabled when using scp
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1"  "$3@$2":~
fi
