#!/usr/bin/env bash

# Install Nginx and configure to a remote server
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx restart
