#!/usr/bin/env bash
# Configure web-02 to be identical to web-01.
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
	# Name of custom HTTP header must be X-Served-By
	# Value of the custom HTTP header must be the hostname of the server Nginx is running on

var=$(hostname)
redirect="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
header="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$redirect/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$header/" /etc/nginx/sites-available/default
sudo service nginx start
