#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy
# Listen to web1 and web2 servers
echo "
        listen load_balancer
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 518770-web-01 34.207.237.30:80 check
        server 518770-web-02 100.26.132.36:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
