#!/usr/bin/env bash
# Displays "To infinity nad beyond" indefinitely with
# a sleep 2 in between the iteration
#	Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
