#!/usr/bin/env bash
#Loop from 1 to 20 and displays:
#	"bad luck from China" for 4th iteration
#	"bad luck from Japan" for 9th iteration
#	"bad luck from Italy" for 17th iteration
#using a while loop and case statement

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
