#!/usr/bin/env bash
# Configure SSH configuration file for the local SSH client to
# 	meet needs so that connects to server without a password
HOST *
	PasswordAuthentication no
	IdentifyFile ~/.ssh/school
